[[client]]
  hostname        = "PC-01"
  mac             = "00:50:56:C0:00:08"
  ip              = "192.168.137.100"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-02"
  mac             = "C0:3F:D5:B7:A2:8B"
  ip              = "192.168.137.101"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-03"
  mac             = "F4:B5:20:55:CB:F9"
  ip              = "192.168.137.102"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-04"
  mac             = "F4:B5:20:70:1A:FA"
  ip              = "192.168.137.103"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-05"
  mac             = "F4:B5:20:72:FD:96"
  ip              = "192.168.137.104"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-06"
  mac             = "F4:B5:20:72:A7:54"
  ip              = "192.168.137.105"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-07"
  mac             = "00:0C:29:89:02:81"
  ip              = "192.168.137.106"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = "windows_11_tm"

[[client]]
  hostname        = "PC-08"
  mac             = "F4:B5:20:71:23:E9"
  ip              = "192.168.137.107"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-09"
  mac             = "F4:B5:20:70:1A:3C"
  ip              = "192.168.137.108"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-10"
  mac             = "EB:A3:B4:6E:90:AC"
  ip              = "192.168.137.109"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-11"
  mac             = "38:3D:8D:C8:4C:D9"
  ip              = "192.168.137.110"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-12"
  mac             = "00:0C:29:A4:BC:F2"
  ip              = "192.168.137.111"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = "windows_11_tm"

[[client]]
  hostname        = "PC-13"
  mac             = "7A:2A:0D:E3:02:82"
  ip              = "192.168.137.112"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-14"
  mac             = "21:85:68:1A:77:B2"
  ip              = "192.168.137.113"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-15"
  mac             = "EB:75:1C:4E:25:B2"
  ip              = "192.168.137.114"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-16"
  mac             = "E4:72:42:59:40:D8"
  ip              = "192.168.137.115"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-17"
  mac             = "13:C7:D4:BB:D2:70"
  ip              = "192.168.137.116"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-18"
  mac             = "18:DD:5D:D0:C4:7A"
  ip              = "192.168.137.117"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-19"
  mac             = "00:0C:29:A6:2C:9A"
  ip              = "192.168.137.118"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-20"
  mac             = "00:0C:29:62:B7:B4"
  ip              = "192.168.137.119"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-21"
  mac             = "F4:4D:30:F9:9B:C1"
  ip              = "192.168.137.120"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-22"
  mac             = "F4:4D:30:A7:80:42"
  ip              = "192.168.137.121"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-23"
  mac             = "9C:8A:C0:99:B3:79"
  ip              = "192.168.137.122"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-24"
  mac             = "94:49:9A:36:E8:AE"
  ip              = "192.168.137.123"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-25"
  mac             = "F4:B5:20:70:17:11"
  ip              = "192.168.137.124"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-26"
  mac             = "EB:7A:0F:31:67:D2"
  ip              = "192.168.137.125"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-01"
  mac             = "F8:C9:99:08:A0:23"
  ip              = "192.168.137.126"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-28"
  mac             = "F4:B5:20:70:12:6F"
  ip              = "192.168.137.127"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-29"
  mac             = "F4:B5:20:70:1C:BA"
  ip              = "192.168.137.128"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-30"
  mac             = "F4:B5:20:70:0E:EC"
  ip              = "192.168.137.129"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-31"
  mac             = "BB:15:F6:75:EC:8F"
  ip              = "192.168.137.130"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-32"
  mac             = "F4:B5:20:5C:30:F4"
  ip              = "192.168.137.131"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-33"
  mac             = "BA:A3:81:C0:00:FF"
  ip              = "192.168.137.132"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-34"
  mac             = "85:D4:11:41:A4:B3"
  ip              = "192.168.137.133"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-35"
  mac             = "F4:4D:30:0A:C0:B8"
  ip              = "192.168.137.134"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-36"
  mac             = "F4:B5:20:70:1B:1D"
  ip              = "192.168.137.135"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-37"
  mac             = "F4:B5:20:70:17:DC"
  ip              = "192.168.137.136"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-38"
  mac             = "F4:C0:EF:1B:65:C7"
  ip              = "192.168.137.137"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-39"
  mac             = "22:BC:FC:7D:95:BD"
  ip              = "192.168.137.138"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-40"
  mac             = "00:AB:00:00:00:00"
  ip              = "192.168.137.139"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-41"
  mac             = "03:1B:93:B6:A1:80"
  ip              = "192.168.137.140"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-42"
  mac             = "B0:87:50:5B:9F:F6"
  ip              = "192.168.137.141"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-43"
  mac             = "5D:38:57:85:C6:1E"
  ip              = "192.168.137.142"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-44"
  mac             = "95:52:7A:85:34:70"
  ip              = "192.168.137.143"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-45"
  mac             = "70:37:CF:C5:84:88"
  ip              = "192.168.137.144"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-46"
  mac             = "80:3A:F7:D6:F5:22"
  ip              = "192.168.137.145"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

[[client]]
  hostname        = "PC-47"
  mac             = "21:00:61:53:50:D0"
  ip              = "192.168.137.146"
  gateway         = "192.168.137.1"
  dns             = "8.8.8.8"
  pxe             = "sb-custom"
  bootfile_uefi   = ""
  bootfile_legacy = ""
  bootfile_ipxe   = ""
  next_server     = "192.168.137.1"
  image_manager   = ""

