
[[client]]
hostname = "PC-01"
mac = "00:0C:29:FD:33:58"
ip = "192.168.137.100"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = "windows_11_tm"

[[client]]
hostname = "PC-02"
mac = "00:0C:29:A6:79:74"
ip = "192.168.137.101"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = "windows_11_tm"


[[client]]
hostname = "PC-05"
mac = "F4:B5:20:70:0E:B0"
ip = "192.168.137.102"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""

[[client]]
hostname = "PC-06"
mac = "F4:B5:20:75:D9:14"
ip = "192.168.137.103"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""

[[client]]
hostname = "PC-07"
mac = "F4:B5:20:67:D0:E8"
ip = "192.168.137.104"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""

[[client]]
hostname = "PC-08"
mac = "F4:B5:20:67:CE:0F"
ip = "192.168.137.105"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""

[[client]]
hostname = "PC-09"
mac = "04:7C:16:CF:F6:DC"
ip = "192.168.137.106"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""

[[client]]
hostname = "PC-10"
mac = "F4:B5:20:70:1B:CE"
ip = "192.168.137.107"
gateway = "192.168.137.1"
dns = "8.8.8.8"
pxe = "sb-custom"
bootfile_uefi = ""
bootfile_legacy = ""
bootfile_ipxe = ""
next_server = "192.168.137.1"
image_manager = ""
