[server]
address = "0.0.0.0"
port = 3260
read_cache_gb = 2

[gamedisk_target]
target_iqn = "iqn.2024-01.com.tmdebug:gamedisks"
discovery = true

[[gamedisk]]
physical_disk = '\\.\PhysicalDrive0'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "GameDisk-0"
product_revision = "1.00"

[windows]
target_iqn_prefix = "iqn.2024-01.com.tmdebug:vhd-"
vhd_dir = ""
block_size = 512
vendor_id = "RUSTISCS"
product_id = "WindowsBoot"
product_revision = "1.00"
discovery = false
super_client_ip = ""
super_client_action = ""

[writeback]
writeback_dirs = ['C:\writeback']
max_cache_per_client_gb = 10
max_write_speed_mbps = 20

[image_manager]
w11 = 'E:\W11-23H2-5335.vhd'
13113 = 'E:\Windows 24H2\Windows_24H2_Modern.vhdx'
w11manta = 'E:\Windows 24H2\Windows_24H2_Modern.vhd'

[dhcp]
enabled = true
start_ip = "192.168.137.100"
end_ip = "192.168.137.200"
router = "192.168.137.1"
dns = "8.8.8.8"
next_server = "192.168.137.1"
subnet_mask = "255.255.255.0"
tftp_dir = "pxe"
pxe_default = "sb-custom"
nic_ips = ["192.168.137.1"]
