[server]
address = "0.0.0.0"
port = 3300

[gamedisk_target]
target_iqn = "iqn.2024-01.com.gameserver:gamedisks"
discovery = true

[[gamedisk]]
physical_disk = '\\.\PhysicalDrive1'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "GameDisk-1"
product_revision = "1.00"

[[gamedisk]]
physical_disk = '\\.\PhysicalDrive2'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "GameDisk-2"
product_revision = "1.00"

[windows]
target_iqn_prefix = "iqn.2024-01.com.gameserver:vhd-"
vhd_dir = 'E:\vhd'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "WindowsBoot"
product_revision = "1.00"
discovery = false
super_client_ip = "10.10.10.25"
super_client_action = "none"

[cache]
cache_dir = 'E:\gamedisk-cache'
max_cache_per_client_gb = 50
