[server]
address = "10.10.10.253"
port = 3260
read_cache_gb = 4

[gamedisk_target]
target_iqn = "iqn.2024-01.com.tmdebug:gamedisks"
discovery = true

[[gamedisk]]
physical_disk = '\\.\PhysicalDrive0'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "GameDisk-0"
product_revision = "1.00"

[windows]
target_iqn_prefix = "iqn.2024-01.com.tmdebug:vhd-"
vhd_dir = 'C:\vhd'
block_size = 512
vendor_id = "RUSTISCS"
product_id = "WindowsBoot"
product_revision = "1.00"
discovery = false
super_client_ip = ""
super_client_action = ""

[writeback]
writeback_dirs = ['C:\writeback']
max_cache_per_client_gb = 10
max_write_speed_mbps = 1000

[image_manager]
w11manta222 = 'E:\Windows 24H2\Windows_24H2_Modern.vhd'
w11 = 'E:\W11-23H2-5335.vhd'

[dhcp]
enabled = true
start_ip = "10.10.10.200"
end_ip = "10.10.10.250"
router = "10.10.10.1"
dns = "8.8.8.8"
next_server = "10.10.10.253"
subnet_mask = "255.255.255.0"
tftp_dir = "pxe"
pxe_default = "sb-custom"
nic_ips = ["192.168.137.1", "10.10.10.253"]
